# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_client": "00_jobs.ipynb",
         "MakeSampleDataJob": "00_jobs.ipynb",
         "PreprocessingJob": "00_jobs.ipynb",
         "FeatureCalcJob": "00_jobs.ipynb",
         "TrainingDataJob": "00_jobs.ipynb",
         "__steps__": "06-submit-training-pipeline.ipynb",
         "__api__": "06-submit-training-pipeline.ipynb",
         "logger": "06-submit-training-pipeline.ipynb",
         "OrderRandomSource": "01-create-sample-data.ipynb",
         "run": "04-training-data.ipynb",
         "calculate": "03-feature-calc.ipynb",
         "count_distinct_values": "03-feature-calc.ipynb",
         "num_stats": "03-feature-calc.ipynb",
         "submit": "06-submit-training-pipeline.ipynb"}

modules = ["jobs.py",
           "data/make_sample_data.py",
           "data/preprocess.py",
           "data/feature_calc.py",
           "data/training_data.py",
           "submit_training_pipeline.py"]

doc_url = "https://leosmerling.github.io/fraud_poc/"

git_url = "https://github.com/leosmerling/fraud_poc/tree/master/"

def custom_doc_links(name): return None
