# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = []

# Cell
from hopeit.app.context import EventContext

# Cell
async def get_client(context: EventContext):
    from dask.distributed import Client
    url = context.env['dask']['url']
    if url == "local":
        client = await Client(asynchronous=True)
    else:
        client = await Client(url, asynchronous=True)
    return client
