# AUTOGENERATED! DO NOT EDIT! File to edit: 06-submit-training-pipeline.ipynb (unless otherwise specified).

__all__ = ['__steps__', '__api__', 'logger', 'submit']

# Cell
import dask.dataframe as dd

from hopeit.app.context import EventContext
from hopeit.app.events import Spawn, SHUFFLE
from hopeit.app.api import event_api
from hopeit.app.logger import app_logger

from .jobs import MakeSampleDataJob

# Cell
__steps__ = ['submit']

__api__ = event_api(
    title="Training: Submit training pipeline",
    query_args=[
        ("raw_path", str, "Path to source raw data")
    ],
    responses={
        200: (MakeSampleDataJob, "Job submitted")
    }
)


logger = app_logger()

# Cell
def submit(payload: None, context: EventContext, raw_path: str) -> MakeSampleDataJob:
    job = MakeSampleDataJob(path=raw_path)
    logger.info(context, "Submit {job}...")
    return job